### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
PLease approve. I don't like people.

### CODE REVIEW

**Comment by FolaSoft** [comment]
lgtm champ go make that $$$$$$

**Review by NavidAzodi — APPROVED** [review]
+1

**Comment by hdharia** [comment]
approved.

**Review by FolaSoft — APPROVED** [review]
like said please

**Review by Meggie39 — APPROVED** [review]

**Review by Meggie39 — APPROVED** [review]

**Pull request merged**
